# Generated by Django 5.2.8 on 2025-12-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
